"""Small synthetic race used for a zero-network first run."""

from f1_pitwall.domain import Compound, DriverInfo, LapRecord, RaceDataset, RaceMetadata


def create_demo_dataset() -> RaceDataset:
    """Create deterministic race-like timing data without redistribution concerns."""
    entrants = (
        ("NOR", "Lando Norris", "McLaren", "FF8700", 90_100, Compound.MEDIUM),
        ("RUS", "George Russell", "Mercedes", "27F4D2", 90_230, Compound.MEDIUM),
        ("PIA", "Oscar Piastri", "McLaren", "FF8700", 90_310, Compound.SOFT),
        ("LEC", "Charles Leclerc", "Ferrari", "E8002D", 90_440, Compound.MEDIUM),
        ("VER", "Max Verstappen", "Red Bull Racing", "3671C6", 90_520, Compound.SOFT),
        ("ALO", "Fernando Alonso", "Aston Martin", "229971", 90_780, Compound.HARD),
    )
    drivers = {
        code: DriverInfo(driver_id=code, full_name=name, team_name=team, team_color=color)
        for code, name, team, color, _, _ in entrants
    }
    elapsed = dict.fromkeys(drivers, 0)
    laps: list[LapRecord] = []
    for lap_number in range(1, 31):
        timing: list[tuple[str, int]] = []
        for index, (code, _, _, _, base, starting_compound) in enumerate(entrants):
            pit_lap = 13 + index % 3
            stint = 1 if lap_number <= pit_lap else 2
            tyre_age = lap_number if stint == 1 else lap_number - pit_lap
            compound = starting_compound if stint == 1 else Compound.HARD
            degradation = tyre_age * (65 + index * 7)
            variation = ((lap_number * 97 + index * 41) % 420) - 210
            lap_time = base + degradation + variation
            pit_in = lap_number == pit_lap
            pit_out = lap_number == pit_lap + 1
            if pit_in:
                lap_time += 22_000
            if pit_out:
                lap_time += 3_800
            elapsed[code] += lap_time
            timing.append((code, elapsed[code]))
            laps.append(
                LapRecord(
                    driver_id=code,
                    lap_number=lap_number,
                    source_lap=lap_number,
                    lap_time_ms=lap_time,
                    elapsed_time_ms=elapsed[code],
                    compound=compound,
                    tyre_age_laps=tyre_age,
                    stint=stint,
                    pit_in=pit_in,
                    pit_out=pit_out,
                    track_status="1",
                    is_accurate=not pit_in and not pit_out,
                )
            )
        positions = {
            code: position
            for position, (code, _) in enumerate(sorted(timing, key=lambda item: item[1]), 1)
        }
        for offset in range(len(laps) - len(entrants), len(laps)):
            record = laps[offset]
            laps[offset] = record.model_copy(update={"position": positions[record.driver_id]})

    return RaceDataset(
        metadata=RaceMetadata(
            session_id="DEMO-2026-R",
            year=2026,
            event_name="Pit Wall Demonstration Grand Prix",
            country="Virtual",
            circuit="Development Circuit",
            total_laps=30,
            source="Synthetic fixture generated by f1_pitwall.ingestion.demo",
            data_version="demo-v1",
        ),
        drivers=drivers,
        laps=tuple(laps),
    )
